export const REQUEST_LIST_CHAT = 'REQUEST_LIST_CHAT'
export const LIST_CHAT_FETCH_SUCCESSFULL = 'LIST_CHAT_FETCH_SUCCESSFULL'
export const LIST_CHAT_FETCH_FAIL = 'LIST_CHAT_FETCH_FAIL'
export const LIST_CHAT_HANDLE_ERROR = 'LIST_CHAT_HANDLE_ERROR'
